version: '3.5'

services:
  nginx:
    build: ./services/nginx
    container_name: ${CONTAINER_NAME_NGINX}
    networks:
      cocoa_butter_net:
        ipv4_address: ${INGRESS}
    ports:
      - 80:80
#      - 443:443

  users:
    build: ./services/users
    container_name: ${CONTAINER_NAME_USERS}
    env_file:
      - .env
    networks:
      cocoa_butter_net:
        ipv4_address: ${FLASK_USERS_HOST}
    ports:
      - ${FLASK_USERS_PORT}:${FLASK_USERS_PORT}
    volumes:
      - ./services/users/:/app
    restart: always

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: ${CONTAINER_NAME_DB}
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    networks:
        cocoa_butter_net:
            ipv4_address: ${POSTGRES_HOST}
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${CONTAINER_NAME_PGADMIN}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "6090:80"
    env_file:
      - .env
    networks:
        cocoa_butter_net:
            ipv4_address: ${PGADMIN4_HOST}
    depends_on:
      - db

volumes:
  postgres_data:

networks:
    cocoa_butter_net:
        ipam:
            driver: default
            config:
                - subnet: 192.28.0.0/16